#[tool.black]
#line-length = 79
#target-version = ["py313"]
#skip-string-normalization = false
#skip-magic-trailing-comma = false
#exclude = '''
#/(
#  | \.git
#  | \.venv
#  | \venv
#  | migrations
#)/
#'''

[tool.black]
line-length = 79
target-version = ['py313']
skip-string-normalization = false
skip-magic-trailing-comma = false
include = '\.pyi?$'
